create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
create sequence app_user_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence work_pc_seq start with 1 increment by 50;
create table app_user (id bigint not null, name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table app_user_roles (app_user_id bigint not null, roles_id bigint not null);
create table role (id bigint not null, name varchar(255), primary key (id));
create table work_pc (id bigint not null, name varchar(255), primary key (id));
alter table app_user_roles add constraint FK23e7b5jyl3ql41rk3566gywdd foreign key (roles_id) references role;
alter table app_user_roles add constraint FKkwxexnudtp5gmt82j0qtytnoe foreign key (app_user_id) references app_user;
